services:
  - type: web
    name: amazon-scraper
    env: docker
    buildCommand: docker build -t amazon-scraper-image .
    startCommand: docker run -p $PORT:10000 amazon-scraper-image
    envVars:
      - key: PORT
        value: 10000
    plan: free
